package com.tshirtstore.entity;

public enum CouponErrorCode {
    INVALID_COUPON,
    COUPON_NOT_STARTED,
    COUPON_EXPIRED,
    COUPON_INACTIVE,
    MINIMUM_ORDER_NOT_MET,
    PRODUCT_NOT_ELIGIBLE,
    CATEGORY_NOT_ELIGIBLE,
    GLOBAL_USAGE_LIMIT_REACHED,
    USER_USAGE_LIMIT_REACHED
}
